 {{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.app.name2 }}
  labels:
    version1: {{ .Values.app.version1 }}
{{- with .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml . | nindent 4 }}
{{- end }}
# {{- end }}
