 {{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.app.name1 }}
  labels:
    version2: {{ .Values.app.version2 }}
{{- with .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml . | nindent 4 }}
{{- end }}
# {{- end }}
