apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deploy.name }}-svc
  # version: {{ .Values.deploy.version }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
   version: {{ .Values.deploy.version }}
   app: {{ .Values.deploy.app }}
